
-- audit.sql
CREATE TABLE audit_log (
    Audit_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Table_Name VARCHAR2(100),
    Operation VARCHAR2(10),
    Changed_By VARCHAR2(100),
    Change_Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Old_Value CLOB,
    New_Value CLOB
);
