
-- tables.sql
CREATE TABLE Students (
    Student_ID NUMBER PRIMARY KEY,
    Name VARCHAR2(100),
    Program VARCHAR2(50),
    Year NUMBER,
    Contact VARCHAR2(20)
);

CREATE TABLE Instructors (
    Instructor_ID NUMBER PRIMARY KEY,
    Name VARCHAR2(100),
    Department VARCHAR2(50)
);

CREATE TABLE Courses (
    Course_Code VARCHAR2(10) PRIMARY KEY,
    Title VARCHAR2(100),
    Instructor_ID NUMBER,
    FOREIGN KEY (Instructor_ID) REFERENCES Instructors(Instructor_ID)
);

CREATE TABLE Attendance (
    Attendance_ID NUMBER PRIMARY KEY,
    Student_ID NUMBER,
    Course_Code VARCHAR2(10),
    Attendance_Date DATE,
    Status VARCHAR2(10),
    FOREIGN KEY (Student_ID) REFERENCES Students(Student_ID),
    FOREIGN KEY (Course_Code) REFERENCES Courses(Course_Code)
);

CREATE TABLE Grades (
    Grade_ID NUMBER PRIMARY KEY,
    Student_ID NUMBER,
    Course_Code VARCHAR2(10),
    Exam_Scores NUMBER(5,2),
    Final_Grade CHAR(2),
    FOREIGN KEY (Student_ID) REFERENCES Students(Student_ID),
    FOREIGN KEY (Course_Code) REFERENCES Courses(Course_Code)
);

CREATE TABLE Public_Holidays (
    Holiday_Date DATE PRIMARY KEY
);

CREATE TABLE Audit_Log (
    Log_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Action_Type VARCHAR2(10),
    Table_Name VARCHAR2(50),
    Action_Date DATE,
    Performed_By VARCHAR2(100)
);

CREATE TABLE audit_log (
    Audit_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Table_Name VARCHAR2(100),
    Operation VARCHAR2(10),
    Changed_By VARCHAR2(100),
    Change_Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Old_Value CLOB,
    New_Value CLOB
);
